---
title: "MSc Data Science - University of Dundee"
author: "Peter Moore"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  word_document: default
course: AC53011
studentid: '170000983'
bibliography: skeleton.bib
link-citations: yes
---

```{r r-keep-tidy, include = FALSE}

# This is the Rmarkdown that forms the html that forms the original Python in SSMS presentation
# as the presentation mutates, different branches will be published per venue


options(warn=-1)
rm(list=ls()) #clear variables
cat("\014")  #clear console

```


```{r r-setup-part-1, include=FALSE} 
# we are going to use R, sql and python and we are going to set them up now.

# use the tidyverse library for visual output
require(tidyverse)

# use the reticulate library to speak to python
library(reticulate)

# use dplyr for data transformations
library(dplyr)

# use for image rendering
library(png)
library(grid)

# and immediately deploy reticulate to utilise conda
use_condaenv(condaenv="PyR", required =TRUE)

```

```{python py-setup, include=FALSE}
PATH_FILE="/Users/petermoore/Documents/GitHub/VacationVision/Python"
import os
os.chdir(PATH_FILE)
import sys
sys.path.append(PATH_FILE) #add local directory to path

from constants import DSN, ALCHEMYDSN, pdsn, puser, ppassword

```

```{r r-setup-part-2, include=FALSE} 

# use the DBI and odbc packages to connet to sql from R
#(NB the exact connections.yaml file is not included, for obvious password-related reasons, but I've provided a mock-up in the ODBC folder which you could adapt)
library(DBI) # for SQL database calls
library(odbc) # for R database calls

# get connection variables 
con <- DBI::dbConnect(odbc::odbc(),
                      DSN = py$pdsn,
                      uid = py$puser,
                      pwd = py$ppassword)

# collate these in knitr with all the other chunk options
knitr::opts_chunk$set(tidy = FALSE, 
                      cache.extra = packageVersion('tufte'), 
                      connection = con, 
                      max.print = NA, 
                      fig.pos = 'H',
                      fig.width = 5,
                      fig.height = 5) 
knitr::knit_engines$set(python = reticulate::eng_python)

# set up html
options(htmltools.dir.version = FALSE)


```

## MSc Data Science Project - Pete Moore 
## Vacation Vision: A recommendation engine for the travel industry using twitter-based sentiment analysis; image detection and collaborative filtering





### Appendix X

Matrix of skills used and whether or not I had prior^["Prior" meaning before 1st January 2017] experience.

```{r tables-appendix-skillsmatrix, eval =TRUE, echo=FALSE}
xlSkillsMatrix<-readxl("SkillMatrix.xlsx", sheet = "Skills")
knitr::kable(xlSkillsMatrix, caption = 'Skills Matrix')
```
